### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rmulr** [filipefilardi/whatsapp-broadcast-crawler#3]
Hey,

offtopic, but do you know if its possible to add/remove WhatsApp contact in some automated way using Selenium?

thanks in advance
Roman

**Comment by filipefilardi** [comment]
Hey Roman,

I saw your last answer but I have not had time to debug yet!

I'm not familiar with adding or removing contacts via wpp web, but everything you can do manually with whatsapp web you can automate with selenium for sure.

You're welcome
Filipe

**Comment by rmulr** [comment]
Thanks for your response. I now managed to sync contacts on some emulated device to keep contacts coming from an API updated. Not sure how effective it will be to use selenium now to automate adding/deleting these contacts to/from multiple broadcast lists. But i also cannot see any alternative way to solve this as there seems to be no other way instead of browser automation here.

**Comment by rmulr** [comment]
Hm i noticed you cannot manage contacts on WhatsApp Web, also you cannot manage broadcast lists so i don´t see a way to automate this with Selenium. I really wonder how people doing this... :(
